/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IMdi:formatQuoteOpenOutline': typeof import('~icons/mdi/format-quote-open-outline')['default']
    IMdiArrowRightThick: typeof import('~icons/mdi/arrow-right-thick')['default']
    IMdiChevronDoubleRight: typeof import('~icons/mdi/chevron-double-right')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiInformationSlabCircleOutline: typeof import('~icons/mdi/information-slab-circle-outline')['default']
    IMdiInstagram: typeof import('~icons/mdi/instagram')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IMdiPinterest: typeof import('~icons/mdi/pinterest')['default']
    IMdiRobotExcited: typeof import('~icons/mdi/robot-excited')['default']
    IMdiSend: typeof import('~icons/mdi/send')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    IRiLoader4Line: typeof import('~icons/ri/loader4-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
