/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IMdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    IMdiChevronDoubleRight: typeof import('~icons/mdi/chevron-double-right')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IMdiPinterest: typeof import('~icons/mdi/pinterest')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    IRiLoader4Line: typeof import('~icons/ri/loader4-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
